/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as FormulasRouteImport } from './routes/formulas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PathsPathIdRouteImport } from './routes/paths.$pathId'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons.$lessonId'
import { Route as LearnCourseSlugRouteImport } from './routes/learn.$courseSlug'
import { Route as FormulasNameRouteImport } from './routes/formulas.$name'
import { Route as CertificatesSerialRouteImport } from './routes/certificates.$serial'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminQuizzesRouteImport } from './routes/admin.quizzes'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminLessonsRouteImport } from './routes/admin.lessons'
import { Route as AdminExercisesRouteImport } from './routes/admin.exercises'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminCertificatesRouteImport } from './routes/admin.certificates'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAiUsageRouteImport } from './routes/admin.ai-usage'
import { Route as AdminCoursesIndexRouteImport } from './routes/admin.courses.index'
import { Route as LearnCourseSlugLessonSlugRouteImport } from './routes/learn.$courseSlug.$lessonSlug'
import { Route as AdminQuizzesQuizIdRouteImport } from './routes/admin.quizzes.$quizId'
import { Route as AdminLessonsLessonIdRouteImport } from './routes/admin.lessons.$lessonId'
import { Route as AdminCoursesCourseIdRouteImport } from './routes/admin.courses.$courseId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulasRoute = FormulasRouteImport.update({
  id: '/formulas',
  path: '/formulas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PathsPathIdRoute = PathsPathIdRouteImport.update({
  id: '/$pathId',
  path: '/$pathId',
  getParentRoute: () => PathsRoute,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnCourseSlugRoute = LearnCourseSlugRouteImport.update({
  id: '/$courseSlug',
  path: '/$courseSlug',
  getParentRoute: () => LearnRoute,
} as any)
const FormulasNameRoute = FormulasNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => FormulasRoute,
} as any)
const CertificatesSerialRoute = CertificatesSerialRouteImport.update({
  id: '/certificates/$serial',
  path: '/certificates/$serial',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuizzesRoute = AdminQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLessonsRoute = AdminLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExercisesRoute = AdminExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCertificatesRoute = AdminCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiUsageRoute = AdminAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesIndexRoute = AdminCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCoursesRoute,
} as any)
const LearnCourseSlugLessonSlugRoute =
  LearnCourseSlugLessonSlugRouteImport.update({
    id: '/$lessonSlug',
    path: '/$lessonSlug',
    getParentRoute: () => LearnCourseSlugRoute,
  } as any)
const AdminQuizzesQuizIdRoute = AdminQuizzesQuizIdRouteImport.update({
  id: '/$quizId',
  path: '/$quizId',
  getParentRoute: () => AdminQuizzesRoute,
} as any)
const AdminLessonsLessonIdRoute = AdminLessonsLessonIdRouteImport.update({
  id: '/$lessonId',
  path: '/$lessonId',
  getParentRoute: () => AdminLessonsRoute,
} as any)
const AdminCoursesCourseIdRoute = AdminCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AdminCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/paths': typeof PathsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/lessons': typeof AdminLessonsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/quizzes': typeof AdminQuizzesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/certificates/$serial': typeof CertificatesSerialRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/paths': typeof PathsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/lessons': typeof AdminLessonsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/quizzes': typeof AdminQuizzesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/certificates/$serial': typeof CertificatesSerialRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
  '/admin/courses': typeof AdminCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/formulas': typeof FormulasRouteWithChildren
  '/learn': typeof LearnRouteWithChildren
  '/library': typeof LibraryRoute
  '/paths': typeof PathsRouteWithChildren
  '/pricing': typeof PricingRoute
  '/settings': typeof SettingsRoute
  '/admin/ai-usage': typeof AdminAiUsageRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/certificates': typeof AdminCertificatesRoute
  '/admin/courses': typeof AdminCoursesRouteWithChildren
  '/admin/exercises': typeof AdminExercisesRoute
  '/admin/lessons': typeof AdminLessonsRouteWithChildren
  '/admin/media': typeof AdminMediaRoute
  '/admin/quizzes': typeof AdminQuizzesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/certificates/$serial': typeof CertificatesSerialRoute
  '/formulas/$name': typeof FormulasNameRoute
  '/learn/$courseSlug': typeof LearnCourseSlugRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/courses/$courseId': typeof AdminCoursesCourseIdRoute
  '/admin/lessons/$lessonId': typeof AdminLessonsLessonIdRoute
  '/admin/quizzes/$quizId': typeof AdminQuizzesQuizIdRoute
  '/learn/$courseSlug/$lessonSlug': typeof LearnCourseSlugLessonSlugRoute
  '/admin/courses/': typeof AdminCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/formulas'
    | '/learn'
    | '/library'
    | '/paths'
    | '/pricing'
    | '/settings'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/exercises'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/auth/forgot'
    | '/auth/reset'
    | '/certificates/$serial'
    | '/formulas/$name'
    | '/learn/$courseSlug'
    | '/lessons/$lessonId'
    | '/paths/$pathId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/quizzes/$quizId'
    | '/learn/$courseSlug/$lessonSlug'
    | '/admin/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/formulas'
    | '/learn'
    | '/library'
    | '/paths'
    | '/pricing'
    | '/settings'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/exercises'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/auth/forgot'
    | '/auth/reset'
    | '/certificates/$serial'
    | '/formulas/$name'
    | '/learn/$courseSlug'
    | '/lessons/$lessonId'
    | '/paths/$pathId'
    | '/admin'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/quizzes/$quizId'
    | '/learn/$courseSlug/$lessonSlug'
    | '/admin/courses'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/formulas'
    | '/learn'
    | '/library'
    | '/paths'
    | '/pricing'
    | '/settings'
    | '/admin/ai-usage'
    | '/admin/analytics'
    | '/admin/certificates'
    | '/admin/courses'
    | '/admin/exercises'
    | '/admin/lessons'
    | '/admin/media'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/api/chat'
    | '/auth/forgot'
    | '/auth/reset'
    | '/certificates/$serial'
    | '/formulas/$name'
    | '/learn/$courseSlug'
    | '/lessons/$lessonId'
    | '/paths/$pathId'
    | '/admin/'
    | '/admin/courses/$courseId'
    | '/admin/lessons/$lessonId'
    | '/admin/quizzes/$quizId'
    | '/learn/$courseSlug/$lessonSlug'
    | '/admin/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FormulasRoute: typeof FormulasRouteWithChildren
  LearnRoute: typeof LearnRouteWithChildren
  LibraryRoute: typeof LibraryRoute
  PathsRoute: typeof PathsRouteWithChildren
  PricingRoute: typeof PricingRoute
  SettingsRoute: typeof SettingsRoute
  ApiChatRoute: typeof ApiChatRoute
  CertificatesSerialRoute: typeof CertificatesSerialRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formulas': {
      id: '/formulas'
      path: '/formulas'
      fullPath: '/formulas'
      preLoaderRoute: typeof FormulasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/paths/$pathId': {
      id: '/paths/$pathId'
      path: '/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof PathsPathIdRouteImport
      parentRoute: typeof PathsRoute
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$courseSlug': {
      id: '/learn/$courseSlug'
      path: '/$courseSlug'
      fullPath: '/learn/$courseSlug'
      preLoaderRoute: typeof LearnCourseSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/formulas/$name': {
      id: '/formulas/$name'
      path: '/$name'
      fullPath: '/formulas/$name'
      preLoaderRoute: typeof FormulasNameRouteImport
      parentRoute: typeof FormulasRoute
    }
    '/certificates/$serial': {
      id: '/certificates/$serial'
      path: '/certificates/$serial'
      fullPath: '/certificates/$serial'
      preLoaderRoute: typeof CertificatesSerialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quizzes': {
      id: '/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AdminQuizzesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lessons': {
      id: '/admin/lessons'
      path: '/lessons'
      fullPath: '/admin/lessons'
      preLoaderRoute: typeof AdminLessonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exercises': {
      id: '/admin/exercises'
      path: '/exercises'
      fullPath: '/admin/exercises'
      preLoaderRoute: typeof AdminExercisesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/certificates': {
      id: '/admin/certificates'
      path: '/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-usage': {
      id: '/admin/ai-usage'
      path: '/ai-usage'
      fullPath: '/admin/ai-usage'
      preLoaderRoute: typeof AdminAiUsageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses/': {
      id: '/admin/courses/'
      path: '/'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AdminCoursesIndexRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
    '/learn/$courseSlug/$lessonSlug': {
      id: '/learn/$courseSlug/$lessonSlug'
      path: '/$lessonSlug'
      fullPath: '/learn/$courseSlug/$lessonSlug'
      preLoaderRoute: typeof LearnCourseSlugLessonSlugRouteImport
      parentRoute: typeof LearnCourseSlugRoute
    }
    '/admin/quizzes/$quizId': {
      id: '/admin/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AdminQuizzesQuizIdRouteImport
      parentRoute: typeof AdminQuizzesRoute
    }
    '/admin/lessons/$lessonId': {
      id: '/admin/lessons/$lessonId'
      path: '/$lessonId'
      fullPath: '/admin/lessons/$lessonId'
      preLoaderRoute: typeof AdminLessonsLessonIdRouteImport
      parentRoute: typeof AdminLessonsRoute
    }
    '/admin/courses/$courseId': {
      id: '/admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AdminCoursesCourseIdRouteImport
      parentRoute: typeof AdminCoursesRoute
    }
  }
}

interface AdminCoursesRouteChildren {
  AdminCoursesCourseIdRoute: typeof AdminCoursesCourseIdRoute
  AdminCoursesIndexRoute: typeof AdminCoursesIndexRoute
}

const AdminCoursesRouteChildren: AdminCoursesRouteChildren = {
  AdminCoursesCourseIdRoute: AdminCoursesCourseIdRoute,
  AdminCoursesIndexRoute: AdminCoursesIndexRoute,
}

const AdminCoursesRouteWithChildren = AdminCoursesRoute._addFileChildren(
  AdminCoursesRouteChildren,
)

interface AdminLessonsRouteChildren {
  AdminLessonsLessonIdRoute: typeof AdminLessonsLessonIdRoute
}

const AdminLessonsRouteChildren: AdminLessonsRouteChildren = {
  AdminLessonsLessonIdRoute: AdminLessonsLessonIdRoute,
}

const AdminLessonsRouteWithChildren = AdminLessonsRoute._addFileChildren(
  AdminLessonsRouteChildren,
)

interface AdminQuizzesRouteChildren {
  AdminQuizzesQuizIdRoute: typeof AdminQuizzesQuizIdRoute
}

const AdminQuizzesRouteChildren: AdminQuizzesRouteChildren = {
  AdminQuizzesQuizIdRoute: AdminQuizzesQuizIdRoute,
}

const AdminQuizzesRouteWithChildren = AdminQuizzesRoute._addFileChildren(
  AdminQuizzesRouteChildren,
)

interface AdminRouteChildren {
  AdminAiUsageRoute: typeof AdminAiUsageRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCertificatesRoute: typeof AdminCertificatesRoute
  AdminCoursesRoute: typeof AdminCoursesRouteWithChildren
  AdminExercisesRoute: typeof AdminExercisesRoute
  AdminLessonsRoute: typeof AdminLessonsRouteWithChildren
  AdminMediaRoute: typeof AdminMediaRoute
  AdminQuizzesRoute: typeof AdminQuizzesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiUsageRoute: AdminAiUsageRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCertificatesRoute: AdminCertificatesRoute,
  AdminCoursesRoute: AdminCoursesRouteWithChildren,
  AdminExercisesRoute: AdminExercisesRoute,
  AdminLessonsRoute: AdminLessonsRouteWithChildren,
  AdminMediaRoute: AdminMediaRoute,
  AdminQuizzesRoute: AdminQuizzesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FormulasRouteChildren {
  FormulasNameRoute: typeof FormulasNameRoute
}

const FormulasRouteChildren: FormulasRouteChildren = {
  FormulasNameRoute: FormulasNameRoute,
}

const FormulasRouteWithChildren = FormulasRoute._addFileChildren(
  FormulasRouteChildren,
)

interface LearnCourseSlugRouteChildren {
  LearnCourseSlugLessonSlugRoute: typeof LearnCourseSlugLessonSlugRoute
}

const LearnCourseSlugRouteChildren: LearnCourseSlugRouteChildren = {
  LearnCourseSlugLessonSlugRoute: LearnCourseSlugLessonSlugRoute,
}

const LearnCourseSlugRouteWithChildren = LearnCourseSlugRoute._addFileChildren(
  LearnCourseSlugRouteChildren,
)

interface LearnRouteChildren {
  LearnCourseSlugRoute: typeof LearnCourseSlugRouteWithChildren
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnCourseSlugRoute: LearnCourseSlugRouteWithChildren,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface PathsRouteChildren {
  PathsPathIdRoute: typeof PathsPathIdRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsPathIdRoute: PathsPathIdRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FormulasRoute: FormulasRouteWithChildren,
  LearnRoute: LearnRouteWithChildren,
  LibraryRoute: LibraryRoute,
  PathsRoute: PathsRouteWithChildren,
  PricingRoute: PricingRoute,
  SettingsRoute: SettingsRoute,
  ApiChatRoute: ApiChatRoute,
  CertificatesSerialRoute: CertificatesSerialRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
